/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vevo.hiring.snake;

import com.vevo.hiring.snake.SnakeGame.Direction;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class MySnakeGameTest {

    @Test
    public void testInitialBoard() {
        SnakeGame game = new MySnakeGame(10, 10);
        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n..........\n.....X....\n..........\n..........\n..........\n..........", board);
    }

    @Test
    public void testMoveNorth() {
        SnakeGame game = new MySnakeGame(10, 10);
        game.move(Direction.NORTH, true);

        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n.....X....\n.....X....\n..........\n..........\n..........\n..........", board);
    }

    @Test
    public void testMoveSouth() {
        SnakeGame game = new MySnakeGame(10, 10);
        game.move(Direction.SOUTH, true);

        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n..........\n.....X....\n.....X....\n..........\n..........\n..........", board);
    }

    @Test
    public void testMoveEast() {
        SnakeGame game = new MySnakeGame(10, 10);
        game.move(Direction.EAST, true);

        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n..........\n.....XX...\n..........\n..........\n..........\n..........", board);
    }

    @Test
    public void testMoveWest() {
        SnakeGame game = new MySnakeGame(10, 10);
        game.move(Direction.WEST, true);

        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n..........\n....XX....\n..........\n..........\n..........\n..........", board);
    }

    @Test
    public void testMultipleMoves() {
        SnakeGame game = new MySnakeGame(10, 10);
        game.move(Direction.NORTH, true);

        String board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n..........\n.....X....\n.....X....\n..........\n..........\n..........\n..........", board);

        game.move(Direction.NORTH, false);
        board = game.getGameBoard();
        assertEquals("..........\n..........\n..........\n.....X....\n.....X....\n..........\n..........\n..........\n..........\n..........", board);

        game.move(Direction.NORTH, true);
        board = game.getGameBoard();
        assertEquals("..........\n..........\n.....X....\n.....X....\n.....X....\n..........\n..........\n..........\n..........\n..........", board);

    }
}
